name: vercel preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install vercel cli
        run: pnpm install --global vercel@latest
      - name: pull vercel enviornment information
        run: vercel pull --yes --env=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: build projects artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy projects artifcats to vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

